### ISSUE TITLE
Editor: Data types misses type: object

### ISSUE THREAD

**Issue by slinkydeveloper** [Apicurio/apicurio-studio#487]
When I create a new data type (schemas under components), It doesn't add `type:object` to schema definition

**Comment by EricWittmann** [comment]
FYI - I've fixed this in the `oai-ts-commands` library so the next time a release of that is done this will be addressed.

**Comment by EricWittmann** [comment]
This has been fixed and committed - should be all set for the next release.

**Comment by EricWittmann** [comment]
Thanks for the error report!

**Comment by psychowico** [comment]
@EricWittmann I see the issue is still here, at least for the responses. Shouldn't I be able to choose "object" data type here?

**Comment by EricWittmann** [comment]
At the moment, apicurio doesn't support inline object definitions.  So you would need to create a global data type and then refer to it in the `application/json` media type in your screenshot.  I'd like to support editing an `object` type inline within the response, but it's not yet done.

**Comment by enugentdt** [comment]
Any update on this issue? It's the last thing I need before I rewrite _all_ my documentation using this tool :)

**Comment by EricWittmann** [comment]
Which aspect of this issue do you need?  Are you referring to inline object definitions?  If so, why are reusable definitions not an acceptable alternative?  I'd love to know the use-case so that can influence the priority of the feature.

**Comment by psychowico** [comment]
@EricWittmann 

we already have documentation wrote in OpenAPI manually or by other tools that we would like to reuse. inline object definition is common feature, at least I feel like this.

second problem is that following your advice we fastly have a lot of object definitions that are in real only one-time used definitions. it's make definitions list too long and distracts attention from really useful, commonly used structures in our apis. e.g. instead of have 
only `User` and `ShopItem` common defs, we ending with many less important types: `ResponseXType`, ResponseYType`, `ResponseZType` etc.

**Comment by EricWittmann** [comment]
OK thanks for the feedback, @psychowico - I'm going to open a new feature request to add better support for inline schemas.  I think your reasons for wanting that feature are good. :)

**Comment by ThorstenBux** [comment]
Just referencing your new issue in case someone is looking for it: https://github.com/Apicurio/apicurio-studio/issues/744
