### ISSUE TITLE
Github.com: New private repositories not shown in Repository list

### ISSUE THREAD

**Issue by ablaas-ald** [Apicurio/apicurio-studio#569]
After creating a new Private repository in Github.com, it will not show in the "Publish API" to Github menu:

I've created 2 repos in Github under my user "ablaas-ald":
- Test (Public)
- Stratos (Private)
![image](https://user-images.githubusercontent.com/46496046/51166884-3aff6f80-18a5-11e9-8f71-5368e8c80235.png)

Only `Test` shows in the dropdown menu:
![image](https://user-images.githubusercontent.com/46496046/51166842-1c00dd80-18a5-11e9-9924-61f2d440ceb7.png)

**Comment by EricWittmann** [comment]
Thanks for the bug report.  I can't remember if I tried GitHub private repos or not (I know I tested that with GitLab...).  I'll have a look.

**Comment by ablaas-ald** [comment]
Yes GitLab works with private repo.
Thanks for your response. Anyway not urgent ;)

**Comment by EricWittmann** [comment]
I have fixed this issue in GitHub, but I can't reproduce the problem in Bitbucket.  @RichardCullen can you confirm that BitBucket private repositories are broken?  I've tested with my BB account and my private repositories seem to show up just fine.  I'm going to check in my GH fix and we'll go from there.  If we can confirm that BB has the same problem, let's open up a separate issue.

**Comment by RichardCullen** [comment]
Great work getting GH Private working - thanks!
I'm still not having any luck using a private BitBucket account:
![image](https://user-images.githubusercontent.com/45776269/51572141-96aaa800-1ef8-11e9-95df-315d6a203ad8.png)

**Comment by EricWittmann** [comment]
OK thanks - I've created a separate issue for this:  https://github.com/Apicurio/apicurio-studio/issues/615

**Comment by ablaas-ald** [comment]
Works great! Thanks a lot 👍
