### ISSUE TITLE
Few issues with local GitLab

### ISSUE THREAD

**Issue by stojsavljevic** [Apicurio/apicurio-studio#711]
Hi,
first of all, thanks for the great project.

I experienced few issues with local GitLab and I will list them all here in case I'm missing something obvious.
If necessary, I'll create separate issues.

My environment looks like this:
* CentOS 7.5 64-bit, Docker 18.09.1, Java OpenJDK 1.8
* Apicurio 0.2.25.Final containerized according to https://github.com/Apicurio/apicurio-studio/issues/342#issuecomment-405255779 and integrated with the latest version of PostgreSQL
* Keycloak 4.1.0.Final integrated with the latest version of PostgreSQL
* GitLab 11.8.3 with Redis and PostgreSQL used as described here: https://github.com/sameersbn/docker-gitlab#quick-start

Apicurio is integrated with GitLab according to https://apicurio-studio.readme.io/docs/using-a-local-installation-of-gitlab
The only difference is that I had to set following oauth scopes: `api email read_user openid profile`.

Now, I am able to link GitLab account and I am able to publish.
But few features don't work out for me. The very same features work as expected with public GitHub.

My issues with GitLab:

* Social login doesn't work. Keycloak throws exception:
```
07:52:06,753 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-20) Uncaught server error: java.lang.RuntimeException: No identifier provider for identity.
        at org.keycloak.broker.provider.BrokeredIdentityContext.<init>(BrokeredIdentityContext.java:53)
        at org.keycloak.authentication.authenticators.broker.util.SerializedBrokeredIdentityContext.deserialize(SerializedBrokeredIdentityContext.java:250)
        at org.keycloak.services.resources.LoginActionsService.brokerLoginFlow(LoginActionsService.java:736)
        at org.keycloak.services.resources.LoginActionsService.firstBrokerLoginGet(LoginActionsService.java:683)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:138)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:101)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:406)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:213)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
...
```

* I am able to link GitLab account, but once I unlink it I am unable to link it again. Keycloak throws exception:
```
07:55:59,840 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-57) SQL Error: 0, SQLState: 23505
07:55:59,841 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-57) ERROR: duplicate key value violates unique constraint "constraint_40"
  Detail: Key (identity_provider, user_id)=(gitlab, b9638c3d-fe72-4678-96ef-2bdb7dbf2d4f) already exists.
07:55:59,841 INFO  [org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl] (default task-57) HHH000010: On release of batch it still contained JDBC statements
07:55:59,842 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-57) Failed to make identity provider oauth callback: org.keycloak.models.ModelDuplicateException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:57)
        at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:51)
        at com.sun.proxy.$Proxy68.flush(Unknown Source)
        at org.keycloak.models.jpa.JpaUserProvider.addFederatedIdentity(JpaUserProvider.java:159)
        at org.keycloak.storage.UserStorageManager.addFederatedIdentity(UserStorageManager.java:204)
        at org.keycloak.models.cache.infinispan.UserCacheSession.addFederatedIdentity(UserCacheSession.java:794)
        at org.keycloak.services.resources.IdentityBrokerService.performAccountLinking(IdentityBrokerService.java:913)
        at org.keycloak.services.resources.IdentityBrokerService.authenticated(IdentityBrokerService.java:534)
        at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:419)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:13
...
```

* Importing API from GitLab (URL is like http://my.gitlab.host:10080/my-group/my-project/raw/master/openapi/petstore.yaml) results with exception visible in GUI:
```
io.apicurio.hub.core.exceptions.ServerError: Unexpected server error
	at io.apicurio.hub.api.rest.impl.DesignsResource.importDesignFromUrl(DesignsResource.java:351)
	at io.apicurio.hub.api.rest.impl.DesignsResource.importDesign(DesignsResource.java:190)
	at io.apicurio.hub.api.rest.impl.DesignsResource$Proxy$_$$_WeldClientProxy.importDesign(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:509)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:399)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:363)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:365)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:337)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:310)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:443)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:233)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:139)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:142)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:219)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.apicurio.hub.api.security.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:72)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.filters.DisableCachingFilter.doFilter(DisableCachingFilter.java:66)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.filters.CorsFilter.doFilter(CorsFilter.java:64)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:55)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `io.apicurio.hub.core.beans.OpenApiSharedDocument` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('<!DOCTYPE html> <html class="devise-layout-html"> <head prefix="og')
 at [Source: (StringReader); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1031)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1366)
```

Any help is appriciated.
Thanks!

**Comment by EricWittmann** [comment]
Hey @stojsavljevic thanks for the thorough write-up.  The Keycloak errors are new to me, so I'm going to ask one of the Keycloak guys to come here and have a look and offer any insights.  

The last error indicates that when trying to import the API from GL you're actually getting HTML content back from the GL API.  Is this happening *after* you unlinked your account?  Does it work properly when the account is linked?

**Comment by stojsavljevic** [comment]
Hey @EricWittmann 
Thanks for the instant response.

The last error happens when the account is linked.
I can open the link in other tab, response is plain text (no html tags).

I might be missing something. How is import from SC different but import from usual URL?
E.g. after I import from GH, I still need to define repo for publishing. I'd expect that repo details are filled in for such contracts.

**Comment by EricWittmann** [comment]
OK that's interesting.  Can you provide a screenshot or something of what you see in that other tab?  The plain text w/o html tags?

This is a bit of a tricky area because import from SC **is** different from standard URL import.  The reason is that you might have an API definition in a private repository that Apicurio would not be able to access via URL but **can** access by making an authenticated API call to GL.  This area probably needs some improvement, honestly.

**Comment by stojsavljevic** [comment]
![contract_GitLab](https://user-images.githubusercontent.com/16477626/55610612-942fbe80-5783-11e9-863a-90dcf173bd89.png)

I attached the part of the page in browser. You can also see the content type.
I forgot to mention that this contract is in a private repo on GL.

What I think it's going on here is that Apicurio itself doesn't authenticate properly so it gets error/login page (html).
I'm wondering how Apicurio knows how to fetch a contract when few accounts are linked. In this case contract's url doesn't indicate it's on GL.

**Comment by stojsavljevic** [comment]
BTW, what it concerns the problem with re-linking GL account, it seems to be already reported - https://github.com/Apicurio/apicurio-studio/issues/391#issuecomment-416474181 and https://github.com/Apicurio/apicurio-studio/issues/407

**Comment by EricWittmann** [comment]
I'll have to try and replicate this problem locally.  But since the API definition is found in a private repository, then Apicurio will clearly need to authenticate to GL when accessing the content (which it does via the GL API in this case).  Clearly that API call is not working.

What is the URL of the contract?  You mentioned that the URL doesn't indicate that the resource is on GL.

Hm.. I wonder if what you mean is that the URL doesn't indicate **gitlab.org** and that perhaps our code that attempts to figure out whether to use a standard URL or the GL API to access the content only works when the resource is on GitLab.  That could be the problem - we may need to update that code so that it uses the configured GL URL pattern rather than always checking for **gitlab.org**.

**Comment by stojsavljevic** [comment]
As GL is deployed locally, domain is my local VM and the URL of example contract looks like this:
http://alextest.arch.local:10080/test-group/test-project/raw/master/openapi/petstore.yaml

As you can see, there is no indication of GL.

**Comment by EricWittmann** [comment]
Right - that makes sense.  However, Apicurio is configured with the URL to the local GitLab API.  So I think we should be able to update Apicurio to use that information to detect whether a URL is a local GL URL.  Otherwise this feature will never work, because we won't be able to access private GL repo content.

**Comment by EricWittmann** [comment]
Of course the workaround is to download the API definition and then upload it to Apicurio.  Not the best experience but at least it works....

**Comment by EricWittmann** [comment]
I've started setting this up locally so I can try to reproduce the problems.  We'll see how it goes, but it will have to wait until Monday.  More then. :)

**Comment by EricWittmann** [comment]
I've successfully reproduced the Keycloak social login error with the same stack trace you received.  So the good news is that you're not crazy. ;)  I'm going to try a more recent version of Keycloak and see if that helps.

**Comment by EricWittmann** [comment]
Unfortunately the same social login error happens when using Keycloak version 4.8.3.Final.  I'm going to crack open the keycloak source code and see if I can figure out what's going on there.  Not sure I'll be able to solve that problem, as I don't have much experience with the KC source repo.

In the meantime, I've also confirmed the Apicurio error when trying to import from a private GL project.  I'm sure we've already identified the cause of that one, and it's something I can actually fix.

**Comment by stojsavljevic** [comment]
Cool.
Did you manage to reproduce the issue with re-linking (local) GL account?

**Comment by EricWittmann** [comment]
OK I've fixed the problem with import, although now it requires an additional system property be configured.  I'll update the documentation, but FYI there are now two system properties for each source control system:

1) The URL to the web interface
2) The URL to the API

For GitLab they are actually the same, but for GitHub and Bitbucket they are different.  So it's going to seem stupid for you because you're using GitLab... but now you have to set BOTH of the following system properties:

`apicurio.hub.gitlab.api`
`apicurio.hub.gitlab.ui`

Again, for GitLab you would make them the same.  For example, here is my config when testing locally:

```xml
        <property name="apicurio.hub.gitlab.url" value="http://192.168.1.20:10080"/>
        <property name="apicurio.hub.gitlab.api" value="http://192.168.1.20:10080"/>
```

Now I'm going to dig into KC a little bit and see if I can figure out what's wrong with social login.

**Comment by EricWittmann** [comment]
> Cool.
> Did you manage to reproduce the issue with re-linking (local) GL account?

I haven't tried that yet, but that has been an intermittent problem within Keycloak for a long time now - it's hard to reproduce consistently.  But in this case I haven't tried it yet - it was the lowest priority of the problems you identified. :)

**Comment by EricWittmann** [comment]
I have an update for the social login problem.  It turns out that the GitLab OpenId Connect user info endpoint doesn't return user information in the format that the generic Keycloak OID Connect adapter is expecting.  In particular, the unique ID of the identity is supposed to be returned in a property named `sub` but that is missing from the GitLab impl - they call it `id` instead.  

The Keycloak GitLab adapter handles this properly, which is why it works against gitlab.com but not a local installation.

A crappy workaround is to disable the user info call in the gitlab identity provider settings (in Keycloak):

![image](https://user-images.githubusercontent.com/1890703/55761592-d9771900-5a2d-11e9-8e53-048a6acf2643.png)

That will allow you to login via GitLab, but it will require the user to enter some additional (redundant) information on the **first** login attempt (information that would normally be pulled from the user info service).

I will write this up as a bug in Keycloak and we'll see what they say is the proper path forward.  

If we were so inclined, I suppose we could create a configurable GitLab identity provider, which is one possible solution (the existing Keycloak gitlab identity provider hard-codes the OID Connect URLs to **gitlab.com**).

**Comment by EricWittmann** [comment]
I have filed an issue with the Keycloak project here:

https://issues.jboss.org/browse/KEYCLOAK-10011

Feel free to vote for it or just watch it. :)

**Comment by stojsavljevic** [comment]
Great to hear that! You are the man!

What it concerns the issue with re-linking GL account, in my case, it's not an intermittent problem. I get it every time, even when I clean KC data and create everything from the scratch. The workaround is to re-create the user in KC.
Can you please try to reproduce it on your side? So the issue gets tracked at least.

**Comment by EricWittmann** [comment]
Will do - that was my first task for today.  That said, I reported the UK constraint violation in KC awhile ago:

https://issues.jboss.org/browse/KEYCLOAK-8223

But I didn't have really good steps to reproduce.  So hopefully if we have that now (with this use case) then some progress can be made on the issue.

It's possible/likely that fixing the first problem will actually fix the UK constraint problem as well.  I suspect that account linking is working but the userId is null, leading to a very non-unique key being used in the DB.  But that's just a guess.

In any case, I'll mess around with this now.  I'm also going to look into creating a custom ID Provider class in Keycloak to hopefully solve both problems.

**Comment by EricWittmann** [comment]
OK I have some progress to report here and I hope you might be able to help with verification.  I have created a variant of the Keycloak GitLab social provider that is capable of using a local GitLab installation.   I **think** this solves both of the current KC problems.

It's not hard to use, but requires you to do a few things.  I'll outline the steps below:

1. Clone and build the custom Keycloak provider here:  https://github.com/Apicurio/apicurio-keycloak-extensions
2. Copy the resulting JAR file from `apicurio-keycloak-extensions/social/target/apicurio-keycloak-extensions-social-1.0.0-SNAPSHOT.jar` into your Keycloak installation's `standalone/deployments` directory
3. When you start Keycloak, add the following system property:  `-Dapicurio.hub.gitlab.url=http://local-gitlab.example.org` where the value is obviously the real URL to your local GitLab install
4. When configuring Keycloak, you will now have two "GitLab" options when creating the Identity Provider.  Instead of choosing **GitLab** (or **OpenID Connect v1.0**) instead choose **GitLab (Local)**.
5. All other configuration is the same as normal.

The result of doing this is that you will be using my custom GitLab ID provider impl instead of the Keycloak baked-in impl.  And the only difference between mine and the default is that mine checks for that System Property to determine the location of the various GitLab OpenID Connect endpoints.  So if you start Keycloak with the `apicurio.hub.gitlab.url` system property properly set, everything should work!

Note:  you do **NOT** need to Disable User Info when configuring **GitLab (Local)** (in fact you won't have that option).

**Comment by EricWittmann** [comment]
Oh, I forgot to mention, I was **unable** to reproduce the link->unlink->relink problem you reported (although as I've seen it before I don't doubt that you're seeing it).  If you can provide exactly the steps you take to reproduce that issue, I can add that information to the Keycloak JIRA issue (or you can do it directly yourself).  But I've tried creating three different users in both GitLab and Keycloak and then linking and unlinking all of them in different orders...no problems. :(

**Comment by stojsavljevic** [comment]
Let's say I already have env in place as described https://apicurio-studio.readme.io/docs/using-a-local-installation-of-gitlab
Here are the steps I've just tried:
1) register new user on GL login page
2) add him as a GL group and project member (maintainer)
3) log out of GL
4) register new user in Apicurio (KC) login page with same details as on GL and log in
5) link GL account using newly registered user
6) sign out from GL and Apicurio
7) log in to Apicurio
8) unlink GL account
9) log out from Apicurio and log in again
10) press link button again
11) log in to GL
12) exception happens

The exception happens even with clean KC/Apicurio setup.

IMHO, the most important part of KC's stack trace is this:
```
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "constraint_40"
  Detail: Key (identity_provider, user_id)=(gitlab, 0609a7e3-8825-4b01-aee1-e8933ba5e672) already exists.
```

I noticed that after I unlink GL account for a user, `gitlab` remains as identity provider for the user in KC (KC GUI - Apicurio Realm - Users - user in question - Identity Provider Links).
This doesn't look like the desired behavior. Can you confirm that?

Apicurio's log is not verbose enough. Should I increase the log level in order to get more info and how to do it?

**Comment by EricWittmann** [comment]
Thanks for the detailed steps to reproduce. I'll try this again.

You are right that the identity provider link remains even after unlinking.  The unlinking process only removes the information from the Apicurio database.  When I implemented this there was no API in keycloak that I could use to remove the identity provider link there.  I don't know if that has changed since.

But it's not supposed to matter - if you try to re-link an account, keycloak is supposed to update that information.  Clearly what's happening (under some situations but not others) is that KC is trying to add another row for the link rather than update the existing one.

It is possible to increase the log level, but I don't think it will yield us any additional information in this particular case.

But what I'm really interested in now is whether my [custom GitLab identity provider implementation](https://github.com/Apicurio/apicurio-studio/issues/711#issuecomment-481303701) fixes either (or both??) of the remaining KC problems.

**Comment by stojsavljevic** [comment]
I tried it out and social login with local GL works! Thumbs up!

What it concerns re-linking, it works properly but **only** for those who are logged in using GL's social login. The problem remains for others.

**Comment by EricWittmann** [comment]
OK thanks for the update.  I'm glad the social login works now. :)

I'll see what I can do about getting more Keycloak attention on the re-linking issue.

Question: do you know where the GitLab data is stored when running it via docker compose?  I've pruned all the docker volumes after shutting everything down, but when I re-run the GitLab docker compose, all my created users still exist!

**Comment by stojsavljevic** [comment]
I set up GL using this file: https://raw.githubusercontent.com/sameersbn/docker-gitlab/master/docker-compose.yml
I see that all three services have volumes defined. Isn't that it?

**Comment by EricWittmann** [comment]
I would have thought so (I used the same docker compose as you did) but I can't seem to clean that environment.  It's OK though - I can just use different users each time I test.  But it's very surprising that the data sticks around even after I've shut down all the docker containers, deleted them, and then pruned all the volumes!

**Comment by EricWittmann** [comment]
Ah - it looks like the data actually does stick around in `/srv/docker/gitlab`.  Mystery solved. :)

**Comment by EricWittmann** [comment]
OK I finally got around to trying your steps-to-reproduce **exactly** as you've written them and I was able to reproduce the problem.  Thanks for those.  I'll try to escalate in Keycloak.

**Comment by EricWittmann** [comment]
For tracking purposes:  https://issues.jboss.org/browse/KEYCLOAK-8223

I realized I never linked to it...

**Comment by stojsavljevic** [comment]
Coolio.
You nailed them all so we have one fix, one workaround and one issue reported. Not bad :)

As you said on JBoss issue tracker, steps to reproduce the PK violation error could be simpler. I just wanted to make sure the issue is not caused by front end side.

One last thing, IMHO, the documentation has to be updated with:
* adding extension to KC - fix for social login
* additional configuration (`apicurio.hub.gitlab.url`, `apicurio.hub.gitlab.api`) - fix for import problem
* description of re-link problem
